export const INITIAL_LOAD = "INITIAL_LOAD"
export const ADD_TODO = "ADD_TODO"
export const REMOVE_TODO = "REMOVE_TODO"
export const UPDATE_TODO = "UPDATE_TODO"
export const EDIT_TODO = "EDIT_TODO"
export const UPDATE_STATS = "UPDATE_STATS"
